<?php
require_once 'config.php';
require_once 'status.php';

if (isset($_GET['acct']) && isset($_GET['key'])) {
    $account = $_GET['acct'];
    $key = $_GET['key'];

    $accountFile = "accounts/{$account}";

    if (file_exists($accountFile)) {
        $accountInfo = unserialize(file_get_contents($accountFile));

        // Pass the $key variable when calling the function.
        if ($accountInfo['key'] === $key) {
            outputRssFeed($account, $key);
        } else {
            echo 'Invalid key.';
        }
    } else {
                echo 'Invalid account.';
    }
} else {
    echo 'Missing account or key.';
}

function outputRssFeed($account, $key) {
    $statusFile = "statuses/{$account}";

    $statuses = [];
    if (file_exists($statusFile)) {
        $statuses = unserialize(file_get_contents($statusFile));
    }

    header('Content-Type: application/rss+xml; charset=utf-8');
    echo '<?xml version="1.0" encoding="UTF-8"?>' . PHP_EOL;
    echo '<rss version="2.0">' . PHP_EOL;
    echo '<channel>' . PHP_EOL;

    echo '<title>Facebook Statuses - ' . htmlspecialchars($account) . '</title>' . PHP_EOL;
    echo '<link>' . DOMAIN . '/feeds.php?acct=' . urlencode($account) . '&amp;key=' . urlencode($key) . '</link>' . PHP_EOL;
    echo '<description>Facebook status updates generated by GPT API for ' . htmlspecialchars($account) . '</description>' . PHP_EOL;
    echo '<language>en-us</language>' . PHP_EOL;

    foreach ($statuses as $index => $status) {
        if (!empty($status)) {
            echo '<item>' . PHP_EOL;
            echo '<title>Status ' . ($index + 1) . '</title>' . PHP_EOL;
            echo '<link>' . DOMAIN . '/feeds.php?acct=' . urlencode($account) . '&amp;key=' . urlencode($key) . '</link>' . PHP_EOL;
            echo '<description><![CDATA[' . htmlspecialchars(trim($status)) . ']]></description>' . PHP_EOL;
            echo '<pubDate>' . date('r', time() - (count($statuses) - $index) * 3600) . '</pubDate>' . PHP_EOL;
            echo '</item>' . PHP_EOL;
        }
    }
    echo '</channel>' . PHP_EOL;
    echo '</rss>';
}
